#declare -a arr=("cross_entropy_plot()" "hinge_dqfd_plot()" "hard_Q_plot()" "soft_Q_plot()" "DQfD_no_l2_softQ_plot()" "DQfD_no_l2_plot()" "policy_gradient_soft_1_step_plot()" "exp_policy_grad_weighting_plot()" "exp_advantage_diff_learning_plot()")
#declare -a arr=("policy_gradient_soft_1_step_finetune_small_explore_May16()")
#declare -a arr=("DQFD_no_l2_T()" "DQfD_full_T()")
#declare -a arr=("hard_Q_in_env()" "soft_Q_in_env()")
#declare -a arr=("cross_entropy_dm_finetune_small_explore()" "cross_entropy_dm_finetune_normal_explore()")
#declare -a arr=("cross_entropy_finetune()" "hinge_standard_finetune()" "hard_Q_finetune()")
#declare -a arr=("policy_gradient_soft_1_step_finetune_small_explore_May16" "policy_gradient_soft_1_step_finetune_normal_explore_May16" "adv_learn_finetune_small_explore_May16" "adv_learn_finetune_normal_explore_May16" "exp_policy_grad_weighting_finetune_normal_explore_May16()" "exp_policy_grad_weighting_finetune_small_explore_May16()" "DQfD_no_l2_finetune_small_explore_human_May16()" "DQfD_no_l2_finetune_normal_explore_human_May16()")
## now loop through the above arrayi
#declare -a arr=("dueling_net_double_Q_eval")
#declare -a arr=("urex_multistep")
#declare -a arr=("collect_torcs_demonstration_3e5")
#declare -a arr=("torcs_cross_entropy_demo")
#declare -a arr=("torcs_cross_entropy_demo" "torcs_hinge_dqfd_demo" "torcs_hard_Q_demo" "torcs_soft_Q_demo" "torcs_dqfd_full_demo" "torcs_V_grounding_demo" "torcs_V_grounding_no_weighting_demo" "torcs_PG_demo" "torcs_PG_no_weighting_demo")
#declare -a arr=("torcs_only_V_no_weighting_demo" "torcs_Q_grounding_no_weighting_demo")
#declare -a arr=("torcs_cross_entropy_demo" "torcs_hinge_dqfd_demo" "torcs_hard_Q_demo" "torcs_soft_Q_demo" "torcs_dqfd_full_demo" "torcs_V_grounding_demo" "torcs_V_grounding_no_weighting_demo" "torcs_PG_demo" "torcs_PG_no_weighting_demo" "torcs_only_V_no_weighting_demo" "torcs_Q_grounding_no_weighting_demo")
#declare -a arr=("torcs_PG_no_weighting_demo")
#declare -a arr=("collect_demonstration_enduro")
#declare -a arr=("V_grounding_no_weighting_T" "PG_no_weighting_T" "DQfD_full_T" "cross_entropy_T" )
#declare -a arr=("V_grounding_no_weighting_T")
#declare -a arr=("DQfD_full_T" "cross_entropy_T")
#declare -a arr=("torcs_DQFD_inenv_no_hinge")
#declare -a arr=("torcs_V_grounding_demo_stage_1")
#declare -a arr=("torcs_V_grounding_inenv_stage_2('V_grounding_no_weighting')" "torcs_V_grounding_inenv_stage_2('V_grounding')" "torcs_V_grounding_inenv_stage_2('cross_entropy')" "torcs_V_grounding_inenv_stage_2('hard_Q')" "torcs_V_grounding_inenv_stage_2('dqfd')")
#declare -a arr=("torcs_V_grounding_inenv_stage_2('dqfd')")
#declare -a arr=("torcs_DQFD_inenv_no_hinge_stage_2('V_grounding_no_weighting')" "torcs_DQFD_inenv_no_hinge_stage_2('V_grounding')" "torcs_DQFD_inenv_no_hinge_stage_2('cross_entropy')" "torcs_DQFD_inenv_no_hinge_stage_2('hard_Q')" "torcs_DQFD_inenv_no_hinge_stage_2('dqfd')")
#declare -a arr=("torcs_hard_Q_complex")
#declare -a arr=("torcs_V_grounding_inenv_stage_2_large_replay('V_grounding_no_weighting')" "torcs_V_grounding_inenv_stage_2_large_replay('V_grounding')" "torcs_V_grounding_inenv_stage_2_large_replay('cross_entropy')" "torcs_V_grounding_inenv_stage_2_large_replay('hard_Q')" "torcs_V_grounding_inenv_stage_2_large_replay('dqfd')" "torcs_DQFD_inenv_stage_2_large_replay('V_grounding_no_weighting')" "torcs_DQFD_inenv_stage_2_large_replay('V_grounding')" "torcs_DQFD_inenv_stage_2_large_replay('cross_entropy')" "torcs_DQFD_inenv_stage_2_large_replay('hard_Q')" "torcs_DQFD_inenv_stage_2_large_replay('dqfd')")
#declare -a arr=("collect_torcs_demonstration_complex")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_complex" "torcs_hard_Q_demo_stage_1_complex" "torcs_dqfd_full_demo_stage_1_complex" "torcs_V_grounding_demo_stage_1_complex" "torcs_V_grounding_no_weighting_demo_stage_1_complex")
#declare -a arr=("torcs_hard_Q_slowcar")
#declare -a arr=("torcs_V_grounding_inenv_stage_2_large_replay_complex('V_grounding_no_weighting')" "torcs_V_grounding_inenv_stage_2_large_replay_complex('V_grounding')" "torcs_V_grounding_inenv_stage_2_large_replay_complex('cross_entropy')" "torcs_V_grounding_inenv_stage_2_large_replay_complex('hard_Q')" "torcs_V_grounding_inenv_stage_2_large_replay_complex('dqfd')" "torcs_DQFD_inenv_stage_2_large_replay_complex('V_grounding_no_weighting')" "torcs_DQFD_inenv_stage_2_large_replay_complex('V_grounding')" "torcs_DQFD_inenv_stage_2_large_replay_complex('cross_entropy')" "torcs_DQFD_inenv_stage_2_large_replay_complex('hard_Q')" "torcs_DQFD_inenv_stage_2_large_replay_complex('dqfd')")
#declare -a arr=("torcs_hard_Q_trial")
#declare -a arr=("torcs_hard_Q_trial_perfect" "torcs_hard_Q_trial_imperfect")
#declare -a arr=("torcs_hard_Q_simple_reward")
#declare -a arr=("torcs_hard_Q_trial_perfect_div_100" "torcs_hard_Q_trial_imperfect_div_100" "torcs_hard_Q_trial_perfect" "torcs_hard_Q_trial_imperfect" "torcs_hard_Q_simple_reward_addconst")
#declare -a arr=("torcs_hard_Q_simple_reward_addconst_supermulti")
#declare -a arr=("collect_torcs_demonstration_super_multi")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_supermulti" "torcs_hard_Q_demo_stage_1_supermulti" "torcs_dqfd_full_demo_stage_1_supermulti" "torcs_V_grounding_demo_stage_1_supermulti" "torcs_V_grounding_no_weighting_demo_stage_1_supermulti")
#declare -a arr=("torcs_hard_Q_autoback")
#declare -a arr=("torcs_DQFD_inenv_stage_2_supermulti('V_grounding_no_weighting')" "torcs_DQFD_inenv_stage_2_supermulti('V_grounding')" "torcs_DQFD_inenv_stage_2_supermulti('cross_entropy')" "torcs_DQFD_inenv_stage_2_supermulti('hard_Q')" "torcs_DQFD_inenv_stage_2_supermulti('dqfd')" "torcs_V_grounding_inenv_stage_2_supermulti('V_grounding_no_weighting')" "torcs_V_grounding_inenv_stage_2_supermulti('V_grounding')" "torcs_V_grounding_inenv_stage_2_supermulti('cross_entropy')" "torcs_V_grounding_inenv_stage_2_large_supermulti('hard_Q')" "torcs_V_grounding_inenv_stage_2_supermulti('dqfd')")
#declare -a arr=("torcs_hard_Q_autoback_supermulti")
#declare -a arr=("collect_torcs_demonstration_autoback_simple")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_autoback_simple" "torcs_hard_Q_demo_stage_1_autoback_simple" "torcs_dqfd_full_demo_stage_1_autoback_simple" "torcs_V_grounding_demo_stage_1_autoback_simple" "torcs_V_grounding_no_weighting_demo_stage_1_autoback_simple")
#declare -a arr=("torcs_human_cross_entropy_demo_stage_1" "torcs_human_hard_Q_demo_stage_1" "torcs_human_dqfd_full_demo_stage_1" "torcs_human_V_grounding_demo_stage_1" "torcs_human_V_grounding_no_weighting_demo_stage_1")
#declare -a arr=("collect_torcs_demonstration_autoback_simple_bad")
#declare -a arr=("torcs_V_grounding_no_weighting_demo_stage_1_autoback_simple_bad")
#declare -a arr=("torcs_V_grounding_inenv_stage_2_simple_bad_reduce_variance('V_grounding_no_weighting')")
#declare -a arr=("torcs_V_grounding_inenv_stage_2_simple_bad('V_grounding_no_weighting')" "torcs_V_grounding_inenv_stage_2_simple_bad('V_grounding')" "torcs_V_grounding_inenv_stage_2_simple_bad('cross_entropy')" "torcs_V_grounding_inenv_stage_2_simple_bad('hard_Q')" "torcs_V_grounding_inenv_stage_2('dqfd')")
#declare -a arr=("torcs_DQFD_inenv_stage_2_simple_bad('V_grounding_no_weighting')" "torcs_DQFD_inenv_stage_2_simple_bad('V_grounding')" "torcs_DQFD_inenv_stage_2_simple_bad('cross_entropy')" "torcs_DQFD_inenv_stage_2_simple_bad('hard_Q')" "torcs_DQFD_inenv_stage_2_simple_bad('dqfd')")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_half_amount" "torcs_hard_Q_demo_stage_1_half_amount" "torcs_dqfd_full_demo_stage_1_half_amount" "torcs_V_grounding_demo_stage_1_half_amount" "torcs_V_grounding_no_weighting_demo_stage_1_half_amount")
#declare -a arr=("torcs_hard_Q_autoback_kraken")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_50000_amount" "torcs_hard_Q_demo_stage_1_50000_amount" "torcs_dqfd_full_demo_stage_1_50000_amount" "torcs_V_grounding_demo_stage_1_50000_amount" "torcs_V_grounding_no_weighting_demo_stage_1_50000_amount")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_10000_amount" "torcs_hard_Q_demo_stage_1_10000_amount" "torcs_dqfd_full_demo_stage_1_10000_amount" "torcs_V_grounding_demo_stage_1_10000_amount" "torcs_V_grounding_no_weighting_demo_stage_1_10000_amount")
#declare -a arr=("torcs_soft_Q_simple_demo_stage_1_autoback" "torcs_soft_Q_simple_demo_stage_1_autoback_bad" "torcs_soft_Q_simple_demo_stage_1_half_amount" "torcs_soft_Q_simple_demo_stage_1_50000_amount" "torcs_soft_Q_simple_demo_stage_1_10000_amount")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_autoback_simple_bad" "torcs_hard_Q_demo_stage_1_autoback_simple_bad" "torcs_dqfd_full_demo_stage_1_autoback_simple_bad" "torcs_V_grounding_demo_stage_1_autoback_simple_bad" "torcs_V_grounding_no_weighting_demo_stage_1_autoback_simple_bad")
#declare -a arr=("torcs_V_grounding_inenv_stage_2_simple_bad('V_grounding_no_weighting')" "torcs_V_grounding_inenv_stage_2_simple_bad('V_grounding')" "torcs_V_grounding_inenv_stage_2_simple_bad('cross_entropy')" "torcs_V_grounding_inenv_stage_2_simple_bad('hard_Q')" "torcs_V_grounding_inenv_stage_2('dqfd')" "torcs_V_grounding_inenv_stage_2('soft_Q')")
#declare -a arr=("torcs_DQFD_inenv_stage_2_simple_bad('V_grounding_no_weighting')" "torcs_DQFD_inenv_stage_2_simple_bad('V_grounding')" "torcs_DQFD_inenv_stage_2_simple_bad('cross_entropy')" "torcs_DQFD_inenv_stage_2_simple_bad('hard_Q')" "torcs_DQFD_inenv_stage_2_simple_bad('dqfd')" "torcs_DQFD_inenv_stage_2_simple_bad('soft_Q')")
#declare -a arr=("torcs_V_grounding_inenv_stage_2('soft_Q')")
#declare -a arr=("torcs_DQFD_inenv_stage_2('V_grounding_no_weighting')" "torcs_DQFD_inenv_stage_2('V_grounding')" "torcs_DQFD_inenv_stage_2('cross_entropy')" "torcs_DQFD_inenv_stage_2('hard_Q')" "torcs_DQFD_inenv_stage_2('dqfd')" "torcs_DQFD_inenv_stage_2('soft_Q')")
#declare -a arr=("torcs_human_all_cross_entropy_demo_stage_1" "torcs_human_all_hard_Q_demo_stage_1" "torcs_human_all_dqfd_full_demo_stage_1" "torcs_human_all_V_grounding_demo_stage_1" "torcs_human_all_V_grounding_no_weighting_demo_stage_1" "torcs_human_all_soft_Q_demo_stage_1" "torcs_human_all_cross_entropy_demo_stage_1" "torcs_human_all_hard_Q_demo_stage_1" "torcs_human_all_dqfd_full_demo_stage_1" "torcs_human_all_V_grounding_demo_stage_1" "torcs_human_all_V_grounding_no_weighting_demo_stage_1" "torcs_human_all_soft_Q_demo_stage_1" "torcs_human_all_cross_entropy_demo_stage_1" "torcs_human_all_hard_Q_demo_stage_1" "torcs_human_all_dqfd_full_demo_stage_1" "torcs_human_all_V_grounding_demo_stage_1" "torcs_human_all_V_grounding_no_weighting_demo_stage_1" "torcs_human_all_soft_Q_demo_stage_1" "torcs_human_all_cross_entropy_demo_stage_1" "torcs_human_all_hard_Q_demo_stage_1" "torcs_human_all_dqfd_full_demo_stage_1" "torcs_human_all_V_grounding_demo_stage_1" "torcs_human_all_V_grounding_no_weighting_demo_stage_1" "torcs_human_all_soft_Q_demo_stage_1" "torcs_human_all_cross_entropy_demo_stage_1" "torcs_human_all_hard_Q_demo_stage_1" "torcs_human_all_dqfd_full_demo_stage_1" "torcs_human_all_V_grounding_demo_stage_1" "torcs_human_all_V_grounding_no_weighting_demo_stage_1" "torcs_human_all_soft_Q_demo_stage_1")
#declare -a arr=("torcs_human_all_cross_entropy_demo_stage_1_harry" "torcs_human_all_hard_Q_demo_stage_1_harry" "torcs_human_all_dqfd_full_demo_stage_1_harry" "torcs_human_all_V_grounding_demo_stage_1_harry" "torcs_human_all_V_grounding_no_weighting_demo_stage_1_harry" "torcs_human_all_soft_Q_demo_stage_1_harry")
#declare -a arr=("torcs_human_all_cross_entropy_demo_stage_1_yang" "torcs_human_all_hard_Q_demo_stage_1_yang" "torcs_human_all_dqfd_full_demo_stage_1_yang" "torcs_human_all_V_grounding_demo_stage_1_yang" "torcs_human_all_V_grounding_no_weighting_demo_stage_1_yang" "torcs_human_all_soft_Q_demo_stage_1_yang")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_rerun" "torcs_hard_Q_demo_stage_1_rerun" "torcs_dqfd_full_demo_stage_1_rerun" "torcs_V_grounding_demo_stage_1_rerun" "torcs_V_grounding_no_weighting_demo_stage_1_rerun" "torcs_soft_Q_simple_demo_stage_1_rerun" "torcs_cross_entropy_demo_stage_1_rerun" "torcs_hard_Q_demo_stage_1_rerun" "torcs_dqfd_full_demo_stage_1_rerun" "torcs_V_grounding_demo_stage_1_rerun" "torcs_V_grounding_no_weighting_demo_stage_1_rerun" "torcs_soft_Q_simple_demo_stage_1_rerun" "torcs_cross_entropy_demo_stage_1_rerun" "torcs_hard_Q_demo_stage_1_rerun" "torcs_dqfd_full_demo_stage_1_rerun" "torcs_V_grounding_demo_stage_1_rerun" "torcs_V_grounding_no_weighting_demo_stage_1_rerun" "torcs_soft_Q_simple_demo_stage_1_rerun" "torcs_cross_entropy_demo_stage_1_rerun" "torcs_hard_Q_demo_stage_1_rerun" "torcs_dqfd_full_demo_stage_1_rerun" "torcs_V_grounding_demo_stage_1_rerun" "torcs_V_grounding_no_weighting_demo_stage_1_rerun" "torcs_soft_Q_simple_demo_stage_1_rerun" "torcs_cross_entropy_demo_stage_1_rerun" "torcs_hard_Q_demo_stage_1_rerun" "torcs_dqfd_full_demo_stage_1_rerun" "torcs_V_grounding_demo_stage_1_rerun" "torcs_V_grounding_no_weighting_demo_stage_1_rerun" "torcs_soft_Q_simple_demo_stage_1_rerun")
#declare -a arr=("torcs_human_all_cross_entropy_demo_stage_1_yang_new" "torcs_human_all_hard_Q_demo_stage_1_yang_new" "torcs_human_all_dqfd_full_demo_stage_1_yang_new" "torcs_human_all_V_grounding_demo_stage_1_yang_new" "torcs_human_all_V_grounding_no_weighting_demo_stage_1_yang_new" "torcs_human_all_soft_Q_demo_stage_1_yang_new")
#declare -a arr=("torcs_V_grounding_has_weighting_inenv_stage_2_rerun('0')" "torcs_soft_Q_inenv_stage_2_rerun('0')" "torcs_hard_Q_inenv_stage_2_rerun('0')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('0')" "torcs_DQFD_inenv_stage_2_rerun('0')")
#declare -a arr=("torcs_hard_Q_inenv_stage_2_rerun('0')")
#declare -a arr=("torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('0')")
#declare -a arr=("torcs_human_all_cross_entropy_demo_stage_1_yang_new_second" "torcs_human_all_hard_Q_demo_stage_1_yang_new_second" "torcs_human_all_dqfd_full_demo_stage_1_yang_new_second" "torcs_human_all_V_grounding_demo_stage_1_yang_new_second" "torcs_human_all_V_grounding_no_weighting_demo_stage_1_yang_new_second" "torcs_human_all_soft_Q_demo_stage_1_yang_new_second")
#declare -a arr=("torcs_human_all_cross_entropy_demo_stage_1_hxu_slow" "torcs_human_all_hard_Q_demo_stage_1_hxu_slow" "torcs_human_all_dqfd_full_demo_stage_1_hxu_slow" "torcs_human_all_V_grounding_demo_stage_1_hxu_slow" "torcs_human_all_V_grounding_no_weighting_demo_stage_1_hxu_slow" "torcs_human_all_soft_Q_demo_stage_1_hxu_slow")
#declare -a arr=("torcs_cross_entropy_demo_stage_1_rerun('00')" "torcs_hard_Q_demo_stage_1_rerun('00')" "torcs_dqfd_full_demo_stage_1_rerun('00')" "torcs_V_grounding_demo_stage_1_rerun('00')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('00')" "torcs_soft_Q_simple_demo_stage_1_rerun('00')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('01')" "torcs_hard_Q_demo_stage_1_rerun('01')" "torcs_dqfd_full_demo_stage_1_rerun('01')" "torcs_V_grounding_demo_stage_1_rerun('01')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('01')" "torcs_soft_Q_simple_demo_stage_1_rerun('01')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('02')" "torcs_hard_Q_demo_stage_1_rerun('02')" "torcs_dqfd_full_demo_stage_1_rerun('02')" "torcs_V_grounding_demo_stage_1_rerun('02')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('02')" "torcs_soft_Q_simple_demo_stage_1_rerun('02')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('03')" "torcs_hard_Q_demo_stage_1_rerun('03')" "torcs_dqfd_full_demo_stage_1_rerun('03')" "torcs_V_grounding_demo_stage_1_rerun('03')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('03')" "torcs_soft_Q_simple_demo_stage_1_rerun('03')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('04')" "torcs_hard_Q_demo_stage_1_rerun('04')" "torcs_dqfd_full_demo_stage_1_rerun('04')" "torcs_V_grounding_demo_stage_1_rerun('04')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('04')" "torcs_soft_Q_simple_demo_stage_1_rerun('04')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('05')" "torcs_hard_Q_demo_stage_1_rerun('05')" "torcs_dqfd_full_demo_stage_1_rerun('05')" "torcs_V_grounding_demo_stage_1_rerun('05')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('05')" "torcs_soft_Q_simple_demo_stage_1_rerun('05')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('06')" "torcs_hard_Q_demo_stage_1_rerun('06')" "torcs_dqfd_full_demo_stage_1_rerun('06')" "torcs_V_grounding_demo_stage_1_rerun('06')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('06')" "torcs_soft_Q_simple_demo_stage_1_rerun('06')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('07')" "torcs_hard_Q_demo_stage_1_rerun('07')" "torcs_dqfd_full_demo_stage_1_rerun('07')" "torcs_V_grounding_demo_stage_1_rerun('07')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('07')" "torcs_soft_Q_simple_demo_stage_1_rerun('07')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('08')" "torcs_hard_Q_demo_stage_1_rerun('08')" "torcs_dqfd_full_demo_stage_1_rerun('08')" "torcs_V_grounding_demo_stage_1_rerun('08')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('08')" "torcs_soft_Q_simple_demo_stage_1_rerun('08')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('09')" "torcs_hard_Q_demo_stage_1_rerun('09')" "torcs_dqfd_full_demo_stage_1_rerun('09')" "torcs_V_grounding_demo_stage_1_rerun('09')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('09')" "torcs_soft_Q_simple_demo_stage_1_rerun('09')" \
#                 "torcs_cross_entropy_demo_stage_1_rerun('10')" "torcs_hard_Q_demo_stage_1_rerun('10')" "torcs_dqfd_full_demo_stage_1_rerun('10')" "torcs_V_grounding_demo_stage_1_rerun('10')" "torcs_V_grounding_no_weighting_demo_stage_1_rerun('10')" "torcs_soft_Q_simple_demo_stage_1_rerun('10')")
#declare -a arr=("torcs_V_grounding_has_weighting_inenv_stage_2_rerun('00')" "torcs_soft_Q_inenv_stage_2_rerun('00')" "torcs_hard_Q_inenv_stage_2_rerun('00')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('00')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('00')" "torcs_DQFD_inenv_stage_2_rerun('00')")

#declare -a arr=("torcs_V_grounding_has_weighting_inenv_stage_2_rerun('00')" "torcs_soft_Q_inenv_stage_2_rerun('00')" "torcs_hard_Q_inenv_stage_2_rerun('00')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('00')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('00')" "torcs_DQFD_inenv_stage_2_rerun('00')" \
#                "torcs_V_grounding_has_weighting_inenv_stage_2_rerun('01')" "torcs_soft_Q_inenv_stage_2_rerun('01')" "torcs_hard_Q_inenv_stage_2_rerun('01')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('01')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('01')" "torcs_DQFD_inenv_stage_2_rerun('01')" \
#                "torcs_V_grounding_has_weighting_inenv_stage_2_rerun('02')" "torcs_soft_Q_inenv_stage_2_rerun('02')" "torcs_hard_Q_inenv_stage_2_rerun('02')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('02')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('02')" "torcs_DQFD_inenv_stage_2_rerun('02')" \
#                "torcs_V_grounding_has_weighting_inenv_stage_2_rerun('03')" "torcs_soft_Q_inenv_stage_2_rerun('03')" "torcs_hard_Q_inenv_stage_2_rerun('03')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('03')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('03')" "torcs_DQFD_inenv_stage_2_rerun('03')" \
#                "torcs_V_grounding_has_weighting_inenv_stage_2_rerun('04')" "torcs_soft_Q_inenv_stage_2_rerun('04')" "torcs_hard_Q_inenv_stage_2_rerun('04')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('04')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('04')" "torcs_DQFD_inenv_stage_2_rerun('04')")
#declare -a  arr=("torcs_V_grounding_has_weighting_inenv_stage_2_rerun('05')" "torcs_soft_Q_inenv_stage_2_rerun('05')" "torcs_hard_Q_inenv_stage_2_rerun('05')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('05')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('05')" "torcs_DQFD_inenv_stage_2_rerun('05')" \
#                 "torcs_V_grounding_has_weighting_inenv_stage_2_rerun('06')" "torcs_soft_Q_inenv_stage_2_rerun('06')" "torcs_hard_Q_inenv_stage_2_rerun('06')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('06')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('06')" "torcs_DQFD_inenv_stage_2_rerun('06')" \
#                 "torcs_V_grounding_has_weighting_inenv_stage_2_rerun('07')" "torcs_soft_Q_inenv_stage_2_rerun('07')" "torcs_hard_Q_inenv_stage_2_rerun('07')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('07')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('07')" "torcs_DQFD_inenv_stage_2_rerun('07')" \
#                 "torcs_V_grounding_has_weighting_inenv_stage_2_rerun('08')" "torcs_soft_Q_inenv_stage_2_rerun('08')" "torcs_hard_Q_inenv_stage_2_rerun('08')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('08')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('08')" "torcs_DQFD_inenv_stage_2_rerun('08')" \
#                 "torcs_V_grounding_has_weighting_inenv_stage_2_rerun('09')" "torcs_soft_Q_inenv_stage_2_rerun('09')" "torcs_hard_Q_inenv_stage_2_rerun('09')" "torcs_hard_Q_inenv_stage_2_with_cross_ent_rerun('09')" "torcs_V_grounding_no_weighting_inenv_stage_2_rerun('09')" "torcs_DQFD_inenv_stage_2_rerun('09')" )
#declare -a arr=("torcs_human_all_cross_entropy_demo_stage_1_hxu_slow" "torcs_human_all_hard_Q_demo_stage_1_hxu_slow" "torcs_human_all_dqfd_full_demo_stage_1_hxu_slow" "torcs_human_all_V_grounding_demo_stage_1_hxu_slow" "torcs_human_all_V_grounding_no_weighting_demo_stage_1_hxu_slow" "torcs_human_all_soft_Q_demo_stage_1_hxu_slow")
#declare -a arr=("enduro_cross_entropy_rerun" "enduro_DQfD_full_rerun" "enduro_V_grounding_no_weighting_rerun")
declare -a arr=("torcs_human_all_cross_entropy_demo_stage_1_hxu_slow_decay(0.0005)" "torcs_human_all_hard_Q_demo_stage_1_hxu_slow_decay(0.0005)" "torcs_human_all_dqfd_full_demo_stage_1_hxu_slow_decay(0.0005)" "torcs_human_all_V_grounding_demo_stage_1_hxu_slow_decay(0.0005)" "torcs_human_all_V_grounding_no_weighting_demo_stage_1_hxu_slow_decay(0.0005)" "torcs_human_all_soft_Q_demo_stage_1_hxu_slow_decay(0.0005)")
for i in "${arr[@]}"
do
    python run_dqn_atari.py --config $i &
    sleep 30
    #python run_dqn_atari.py --config $i --dataset_size=300000 --demo_file_path='/data/hxu/cs294-112/hw3/link_data/bad_demo_50000.0_0.3' &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --core_num=1 --demo_file_path='/data/hxu/cs294-112/hw3/link_data/bad_demo_150000.0_0.7' &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --core_num=2 --demo_file_path='/data/hxu/cs294-112/hw3/link_data/bad_demo_250000.0_0.7' &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --core_num=3 --demo_file_path='/data/hxu/cs294-112/hw3/link_data/bad_demo_50000.0_0.3' &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --core_num=0 --demo_file_path='/data/hxu/cs294-112/hw3/link_data/bad_demo_150000.0_0.3' &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --core_num=1 --demo_file_path='/data/hxu/cs294-112/hw3/link_data/bad_demo_250000.0_0.3' &
	#python run_dqn_atari.py --config $i --dataset_size=300000 --bad_portion=0 --bad_starts=1.5e5 --tiny_explore=0.7 --core_num=1 &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --bad_portion=0 --bad_starts=0.5e5 --tiny_explore=0.7 --core_num=2 &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --bad_portion=0 --bad_starts=2.5e5 --tiny_explore=0.3 --core_num=3 &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --bad_portion=0 --bad_starts=1.5e5 --tiny_explore=0.3 --core_num=0 &
    #python run_dqn_atari.py --config $i --dataset_size=300000 --bad_portion=0 --bad_starts=0.5e5 --tiny_explore=0.3 --core_num=1 &
done
